#!/usr/bin/env bash
export XIRSYS_IDENT = ""
export XIRSYS_SECRET = ""
export XIRSYS_DOMAIN = ""
export XIRSYS_APP = ""
export XIRSYS_ROOM = ""
export XIRSYS_SECURE = ""
export XIRSYS_HOST = ""
export XIRSYS_PORT = ""
export XIRSYS_PATH = ""
export XIRSYS_METHOD = ""
export XIRSYS_CONTENT_TYPE = ""
export PORT = ""
export HOST = ""
export XIRSYS_PATH = ""
export XIRSYS_PATH = ""
npm start